# Generated by Django 4.1 on 2022-08-17 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('location', models.CharField(max_length=100, verbose_name='Город')),
                ('logo', models.ImageField(upload_to='company_images', verbose_name='Логотипчик')),
                ('description', models.TextField(verbose_name='Информация о компании')),
                ('employee_count', models.IntegerField(verbose_name='Количество сотрудников')),
                ('owner', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=255, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('picture', models.ImageField(upload_to='speciality_images', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название вакансии')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('description', models.TextField(verbose_name='Текст')),
                ('salary_min', models.IntegerField(verbose_name='Зарплата от')),
                ('salary_max', models.IntegerField(verbose_name='Зарплата до')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Опубликовано')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancy.company', verbose_name='Компания')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancy.specialty', verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=255, verbose_name='Имя')),
                ('written_phone', phone_field.models.PhoneField(max_length=31, verbose_name='Телефон')),
                ('written_cover_letter', models.TextField(verbose_name='Сопроводительное письмо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancy.vacancy', verbose_name='Вакансия')),
            ],
        ),
    ]
