# Generated by Django 4.1 on 2022-08-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
    ]
